using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;


public class InventoryManager : MonoBehaviour
{
    public static InventoryManager Instance;
    public List<Item> Items = new List<Item>();
    public Transform ItemContent;
    public GameObject InventoryItem;
    public GameObject inventoryUI;
    private bool inventoryOpen = false;
    public PlayerController playerController;
    public Toggle EnableRemove;
    public InventoryItemController[] InventoryItems;


    private void Awake()
    {
        Instance = this;

        playerController = FindAnyObjectByType<PlayerController>();

        if (FindAnyObjectByType<ItemDrop>() == null) 
        { 
            gameObject.AddComponent<ItemDrop>(); 
        }
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.I))
        {
            ToggleInventory();
        }
    }

    public void Add(Item item)
    {
        Items.Add(item);
    }

    public void Remove(Item item)
    {
        Items.Remove(item);
    }

    public void ListItems()
    {
        foreach (Transform item in ItemContent)
        {
            Destroy(item.gameObject);
        }

        foreach (var item in Items)
        {
            GameObject obj = Instantiate(InventoryItem, ItemContent);
            var itemName = obj.transform.Find("ItemName").GetComponent<TextMeshProUGUI>();
            var itemIcon = obj.transform.Find("ItemIcon").GetComponent<Image>();
            var removeButton = obj.transform.Find("RemoveButton").GetComponent<Button>();

            itemName.text = item.itemName;
            itemIcon.sprite = item.icon;

            if (EnableRemove.isOn)
            {
                removeButton.gameObject.SetActive(true);
            }
        }

        SetInventoryItems();
    }
    
    public void ToggleInventory() 
    { 
        inventoryOpen = !inventoryOpen; 
        inventoryUI.SetActive(inventoryOpen); 
        Cursor.lockState = inventoryOpen ? CursorLockMode.None : CursorLockMode.Locked; 
        Cursor.visible = inventoryOpen; 
        playerController.EnableMovement(!inventoryOpen); 
        
        if (inventoryOpen) 
        { 
            ListItems(); 
        } 
    }

    public void EnableItemsRemove()
    {
        if (EnableRemove.isOn)
        {
            foreach (Transform item in ItemContent)
            {
                item.Find("RemoveButton").gameObject.SetActive(true);
            }
        }
        else
        {
            foreach (Transform item in ItemContent)
            {
                item.Find("RemoveButton").gameObject.SetActive(false);
            }
        }
    }

    public void SetInventoryItems()
    {
        InventoryItems = ItemContent.GetComponentsInChildren<InventoryItemController>();

        for (int i = 0; i < Items.Count; i++)
        {
            InventoryItems[i].AddItem(Items[i]);
        }
    }

}
